### ISSUE TITLE
Understanding the gamma symbol in the transverse rate section

### ISSUE THREAD

**Issue by Joosty** [angadhn/variable-mass-systems-book#1]
While I can see that gamma is defined mathematically to facilitate calculation, is there a contextual explanation for what this term represents or what its units are? If there is it would really help my understanding. 

See the section I'm talking about below:
![Capture](https://github.com/user-attachments/assets/25b2db89-e679-4caf-8bd4-93ae6fb2bb7f)

**Comment by angadhn** [comment]
The purpose of $\Gamma$ is to merely serve as shorthand so Equation (20) is: easy to read; and also easier to interpret because $\Gamma$ determines amplitude of the solution to $\omega_c$. You may find Wang and Eke's paper on axisymmetric variable mass systems useful reading but it might actually also be worth reading a section on geometry of motion of axisymmetric torque-free rigid bodies.
